### ISSUE TITLE
WebView2 Unable to cast COM object of type

### ISSUE THREAD

**Issue by jadav1982** [MicrosoftEdge/WebView2Samples#67]
I am getting below error.

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.WinForms.WebView2.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

**Comment by hunkydoryrepair** [comment]
This happened for me when clicking the Events button.

**Comment by HoldenPCaulfield** [comment]
I have this issue as well.   Does anyone know what to do with this error?

**Comment by jadav1982** [comment]
@hunkydoryrepair and @HoldenPCaulfield  I have move in CefSharp control

**Comment by HoldenPCaulfield** [comment]
> @hunkydoryrepair and @HoldenPCaulfield I have move in CefSharp control

What?

**Comment by jadav1982** [comment]
@HoldenPCaulfield Now i am using cefsharp control

https://cefsharp.github.io/

**Comment by champnic** [comment]
For those still hitting this issue, can you add info about what version of the SDK you are using, as well as what version of the WebView2 Runtime/Edge Browser? Thanks!

**Comment by HoldenPCaulfield** [comment]
I have this issue.  I split out the project: **WebView2WindowsFormsBrowser** into a separate solution.  This project has the issue.  I am not an expert in C#, .Net nor COM, however I have been programming for 50+ years.   I am learning how to instrument the Edge browser with WebView2 in order to make rapid bookings at my golf course in order to beat the other golfers who need to walk through page after page of crap like "who are you playing with" and select a name from a drop-down list of 500 golfers--which takes a lot of time.  I want the 10am spot; I don't want others to get it.  lol.   With WebView2, I can be first to the 10am slot every day and nobody else will be able to beat me to the slot because I will be powered by the powerful WebView2 control and the powerful .Net framework and the powerful language called C# and the powerful platform from Redmond!! 

I have made it work, actually, but needed to put a Try-Catch block around the code at: 
        private void SubscribeToAllEventsOnObject(string name, object target)
        {
             int i = 0;
            foreach (EventInfo eventInfo in target.GetType().GetEvents())
            {
                i+=1;
                tweet("Name: " + name);
                EventHandlerContext context = new EventHandlerContext(this, name + eventInfo.Name);
                MethodInfo methodInfo = context.GetType().GetMethod("HandleEvent");
                Delegate handler = Delegate.
                    (eventInfo.EventHandlerType, context, methodInfo);
                try
                {
                    eventInfo.AddEventHandler(target, handler);
                }
                catch(Exception e)
                {
                    tweet(e.Message); // tweet is my code to show what is going on
                }
            }
        }
Here is a snippet of the error: 
![image](https://user-images.githubusercontent.com/44578831/103841372-6f0b6680-5061-11eb-8fcd-b85a6e44c5da.png)


.  I am so pleased.  Here is my platform on Windows 10:: 
_> Microsoft Visual Studio Community 2019
> Version 16.8.3
> VisualStudio.16.Release/16.8.3+30804.86
> Microsoft .NET Framework
> Version 4.8.04084
> 
> Installed Version: Community
> 
> Visual C++ 2019   00435-60000-00000-AA210
> Microsoft Visual C++ 2019_

cheers fellow programmers.  Trying to figure wtf Delegates are.  lol.

**Comment by HoldenPCaulfield** [comment]
Here is another screen clip of a trace when the delegates are assigned:
![image](https://user-images.githubusercontent.com/44578831/103842310-a0853180-5063-11eb-9aef-f85681339720.png)

**Comment by champnic** [comment]
@HoldenPCaulfield "Tweet" is a much better name for that type of function than regular "log"! 👍 

It looks like it's failing to find the CoreWebView2.WebResourceResponseReceived and CoreWebView2.DOMContentLoaded events. Those are both relatively new events, so my guess is you just need to use a newer version of the runtimethat has support for those. Can you try installing Microsoft Edge Canary or Dev?
https://www.microsoftedgeinsider.com/en-us/download/

**Comment by HoldenPCaulfield** [comment]
Hi Nic:
Many thanks for responding to my post at GitHub.  I appreciate your help.
I downloaded Canary and re-ran the demo app: WebView2WindowsFormsBrowser.
I get the same faults when I click on Events on the BrowserForm screen.  See here:
[cid:image001.png@01D6E533.C52FB820]
Essentially, the sample application works okay, but the EventMonitor form seems to have issues.

The WebView2 component I am using is as follows:
[cid:image003.png@01D6E534.03A4F250] .

Further thoughts are welcome,

Tim

**Comment by champnic** [comment]
@HoldenPCaulfield The images were unable to load (maybe because of email) - if you respond directly on github.com you should be able to include the images again.

If the sample app continues to work fine and it's just reporting there was an exception, I think that may be By Design as expected exceptions while doing feature detection. I'll file a bug on our backlog to take a closer look though. Thanks for the report!

**Comment by HoldenPCaulfield** [comment]
Here is a snip of where I get a fault.   It seems to me that there issues in the EventMonitor class/form with the lists and with obtaining references to the WebView2 methods and properties.  
![image](https://user-images.githubusercontent.com/44578831/104143552-f7557880-538d-11eb-957e-7a5363b0cc47.png)

**Comment by jeremy-marcus** [comment]
Is there any update on this exception? I'm seeing this myself with the latest (stable) version.

**Comment by champnic** [comment]
This looks like it's maybe the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/1971. Are you using an ElementHost?

**Comment by jeremy-marcus** [comment]
I am not using an `ElementHost`.

**Comment by champnic** [comment]
@jeremy-marcus Do you know what is calling "Dispose" in your stack? Are you manually calling it from your code, while a parent is being disposed, or is it being called by the finalizer?

**Comment by champnic** [comment]
We have seen issues in the past where the finalizer calls dispose on a thread different than the UI thread. Can you try calling "Dispose" on the WebView2 control from the UI thread before the finalizer gets to it? We are looking into some potential fixes that would limit this issue.
